services:
  shipment_postgres:
    image: postgres:alpine
    container_name: shipment_postgres
    environment:
      POSTGRES_USER: ${SHIPMENT_PG_USER}
      POSTGRES_PASSWORD: ${SHIPMENT_PG_PASSWORD}
      POSTGRES_DB: ${SHIPMENT_PG_DB_NAME}
    ports:
      - "${SHIPMENT_PG_PORT}:5432"
    volumes:
      - ./data/shipment_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  inventory_registry_postgres:
    image: postgres:alpine
    container_name: inventory_registry_postgres
    environment:
      POSTGRES_USER: ${INVENTORY_REGISTRY_PG_USER}
      POSTGRES_PASSWORD: ${INVENTORY_REGISTRY_PG_PASSWORD}
      POSTGRES_DB: ${INVENTORY_REGISTRY_PG_DB_NAME}
    ports:
      - "${INVENTORY_REGISTRY_PG_PORT}:5432"
    volumes:
      - ./data/inventory_registry_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  inventory_registry_etcd:
    image: bitnami/etcd:3.5.17
    container_name: inventory_registry_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://inventory_registry_etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "${REGISTRY_ETCD_PORT:-2379}:2379"
    volumes:
      - ./data/inventory_registry_etcd:/bitnami/etcd
    restart: unless-stopped

  shipment_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "shipment_rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    volumes:
      - ./data/shipment_queue/data/:/var/lib/rabbitmq/
      - ./data/shipment_queue/log/:/var/log/rabbitmq
      - ./config/shipment_rabbitmq_definitions.json:/etc/rabbitmq/definitions.json:ro

volumes:
  shipment_postgres_data:
    name: shipment_postgres_data
  inventory_registry_etcd:
    name: inventory_registry_etcd
  shipment_queue_data:
    name: shipment_queue_data
  shipment_queue_log:
    name: shipment_queue_log
