version: "3.8"

services:
  inventory_postgres:
    image: postgres:alpine
    container_name: inventory_postgres
    environment:
      POSTGRES_USER: ${INVENTORY_PG_USER}
      POSTGRES_PASSWORD: ${INVENTORY_PG_PASSWORD}
      POSTGRES_DB: ${INVENTORY_PG_DB}
    ports:
      - "${INVENTORY_PG_PORT}:5432"
    volumes:
      - ./data/inventory_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  shipment_postgres:
    image: postgres:alpine
    container_name: shipment_postgres
    environment:
      POSTGRES_USER: ${SHIPMENT_PG_USER}
      POSTGRES_PASSWORD: ${SHIPMENT_PG_PASSWORD}
      POSTGRES_DB: ${SHIPMENT_PG_DB}
    ports:
      - "${SHIPMENT_PG_PORT}:5432"
    volumes:
      - ./data/shipment_postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  inventory_postgres_data:
    name: inventory_postgres_data
  shipment_postgres_data:
    name: shipment_postgres_data
