DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS performance_reports;
DROP TABLE IF EXISTS transport_schedules;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS warehouse_connections;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS carriers;
DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS accounts; 